server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shoe-store
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

security:
  jwt:
    key:
      private: a7cd9a706ef86ecded8251625f9429f87fc91ca4ff7540c0f8a23c6da9a26bc5
      expiration: 1800000
    user:
      generator: AUTH0JWT-BACKEND
